name: LiarsBar
version: '${version}'
main: dk.martinersej.liarsbar.LiarsBar
load: POSTWORLD
depend:
  - WorldEdit
softdepend:
  - Citizens

commands:
  gm:
    description: 'Change gamemode'
    usage: '/gamemode <gamemode>'
    permission: 'liarsbar.gamemode'
  test:
    description: 'Test command'
    usage: '/test'
    permission: 'liarsbar.test'